// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPPaAQ4Vt4niMUJ9QzT_I13Ol8Igf4C00',
    appId: '1:431661313291:web:2af4e798c485b77dbe860e',
    messagingSenderId: '431661313291',
    projectId: 'movies-fbd43',
    authDomain: 'movies-fbd43.firebaseapp.com',
    storageBucket: 'movies-fbd43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_msbN6MshWuoYQZBUeXE7QePbajAU5Lg',
    appId: '1:431661313291:android:b8e055470996da7abe860e',
    messagingSenderId: '431661313291',
    projectId: 'movies-fbd43',
    storageBucket: 'movies-fbd43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMN65rL5wS0sTmctrIqMKFH-AI_PAu9wM',
    appId: '1:431661313291:ios:dccb3d553f855520be860e',
    messagingSenderId: '431661313291',
    projectId: 'movies-fbd43',
    storageBucket: 'movies-fbd43.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMN65rL5wS0sTmctrIqMKFH-AI_PAu9wM',
    appId: '1:431661313291:ios:dccb3d553f855520be860e',
    messagingSenderId: '431661313291',
    projectId: 'movies-fbd43',
    storageBucket: 'movies-fbd43.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPPaAQ4Vt4niMUJ9QzT_I13Ol8Igf4C00',
    appId: '1:431661313291:web:ce9c3bdca3836812be860e',
    messagingSenderId: '431661313291',
    projectId: 'movies-fbd43',
    authDomain: 'movies-fbd43.firebaseapp.com',
    storageBucket: 'movies-fbd43.appspot.com',
  );
}
